########################################################
# SAFCO FINTECH LMS - Frontend Docker Compose
########################################################
version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: safco-frontend
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NEXT_PUBLIC_API_URL=http://safco-app:80/api
      - NODE_ENV=production
    networks:
      - safco-network

networks:
  safco-network:
    external: true
    name: backend_safco
